### ISSUE TITLE
Invariant Violation: View config getter callback for component `RCTModalHostView` must be a function (received `undefined`)

### ISSUE THREAD

**Issue by NidheeshVenugopal** [Finicity/connect-react-native-sdk#2]
Im getting Invariant Violation: View config getter callback for component `RCTModalHostView` must be a function (received `undefined`) issue when I tried to call 
<FinicityConnect
      connectUrl={'my url'}
      eventHandlers={eventHandlers}
      linkingUri={'#UNIVERSAL_LINK#'}
    ></FinicityConnect>

im getting this same issue on both iOS and Android

dependencies in my package.json are

  "@finicity/connect-react-native-sdk": "^1.0.0-rc.4",
    "react": "17.0.1",
    "react-native": "0.64.0",
    "react-native-inappbrowser-reborn": "^3.5.1",
    "react-native-webview": "^11.4.3"

**Comment by alexsalido** [comment]
@NidheeshVenugopal The SDK is only compatible with React v16 at the moment.
